### ISSUE TITLE
Megaloot not spawning in structures spawned by ruins/recurrentcomplex and roguelike dungeons

### ISSUE THREAD

**Issue by Budhvin** [Zairus/MegaLoot#11]

**Comment by Budhvin** [comment]
in order to see megaloot items in chests, is it possible to adjust megaloot settings instead of structure spawner mods?

**Comment by WinterGrave** [comment]
Hi there, for the moment MegaLoot items are sorted when opening standard vanilla loot chests like Villages, Strongholds, Dungeons, End cities, etc. To get them spawning in other mod structures like Rouge Like Dungeons, you need to adjust the loot tables of those mods. Some time in the future we will work a way to handle where items spawn. Thank you!
