### ISSUE TITLE
Jetpack too loud

### ISSUE THREAD

**Issue by gloomyMoron** [Zairus/MegaLoot#13]
I just got a piece of armor that has a Jetpack on it and it is way too loud. I have my Master Volume at 25% and it is still jarringly loud. Other sound settings are, even though I doubt many of them are pertinent but for completeness sake:

- Music: 2% 
- Weather: 35%
- Hostile Creatures: 90%
- Players: 95%
- Voice/Speech: 40%
- Jukebox/Note Blocks: 40%
- Blocks: 50%
- Friendly Creatures: 35%
- Ambient/Environment: 50%

Edit: Well, it would seem it is because I'm using an older version (the one in FC3 1.4.4)... guess this was already noticed and fixed and I'll be going to the next version.

**Comment by WinterGrave** [comment]
On the latest version I removed the sound entirely.
