### ISSUE TITLE
Not technically a bug but question!

### ISSUE THREAD

**Issue by strikerrocker** [Zairus/MegaLoot#3]
Would you accept my Pull Request on various things in this mod using deprecated thinks like not using json recipes and mot using registry events. If so i can sumbit a few pull request on these to improve the overall code quality. I wanted to make sure that i wouldnt waste time doing a PR which wouldn't be accepted.  If no i have no problem.

**Comment by WinterGrave** [comment]
Hi, I'm already in the process of changing to json recipes on all my mods, but I'm open to any improvements, I thin  I am using the registry events for items and blocks in the last push, although I had a little trouble detecting where and how to register tile entities :P if you can help on that I'd be ok with it, if there are any conflicts with the PR I will try to sort it as best as possible, I'm not a pro on git. Thanks!

**Comment by strikerrocker** [comment]
Tile entities are registered in block registry after you register the blocks associated with them.

**Comment by strikerrocker** [comment]
If you have anymore doubt here is an discord consisting of modders who can help with situations from starters to advanced modding : https://discord.gg/ZwyDK96 This is it for this issue thanks for taking my suggestions
