### ISSUE TITLE
Hover Armor messes with movement controls

### ISSUE THREAD

**Issue by Fabbi** [Zairus/MegaLoot#6]
# Version: 1.12.2-0.2.24
While having armor with `hover` ability equipped, the diagonal movement is broken. Pressing `left` or `right` will almost cancel all other movement.

## Reproduce
Armor has `Hover:5, Speed:2`

- equip armor
- walk forward (everything is fine)
- press left or right (forward movement is almost gone)

I `tp`'d myself to a corner of a block, looked `0 / 90` forward/down and pressed `w`+`d` at the same time. It takes ~15 Blocks to the right until I moved one block forward.

**Comment by WinterGrave** [comment]
Was fixed in 0.2.26
