### ISSUE TITLE
[Request] Configs to control jetpack speed / use fuel / disable

### ISSUE THREAD

**Issue by Alaberti** [Zairus/MegaLoot#8]
Please and thank you! We'd like to make these balanced according to our pack, and right now they're easy to find and as they don't require fuel and are decently fast, there's little incentive to explore other alternatives. Thanks!

**Comment by WinterGrave** [comment]
We will consider this in order to fit different modpacks

**Comment by demfels** [comment]
This would be awesome if we could include config on which upgrades are available or not in the modpack.  Thanks!
