### ISSUE TITLE
Mega Loot Crashing on 1.12.2

### ISSUE THREAD

**Issue by samolego** [Zairus/MegaLoot#9]
Hi!

I discovered this mod some time ago and now I cannot get it to work. Even if I launch the game with just this mod, it crashes ... Below is the crash text ...

Mod version: megaloot-1.12.2-0.2.27
Forge version: 14.23.4.2705

https://gist.github.com/samolego/f48ef133c5be672889018b959a185b19

**Comment by Shadows-of-Fire** [comment]
The mod depends on baubles, which you don't have installed

**Comment by WinterGrave** [comment]
Hi, yes, it depends on baubles, it is listed as a dependency on curse project page.

**Comment by samolego** [comment]
Oh, I am so sorry, I have downloaded it from curseforge where I didn't find the requirement - baubles ... Thank you so much!

**Comment by samolego** [comment]
I think that my game just crashed, there wasn't any screen popping up as far as I remember ...
